### ISSUE TITLE
After successful install and npm run dev Error can not /GET 

### ISSUE THREAD

**Issue by mikimaine** [rorikurniadi/vuejs-AdminLTE#3]
after i have downloaded and install all dependency from npm and bower then run grunt shows me green.
after that i run npm run dev  it told me my development server is on http://localhost:3123 but when i hit that url i get  `Cannot GET /`

**Comment by webgodo** [comment]
Me too!

What should we do?

**Comment by r0r1** [comment]
Hi @mikimaine & @webgodo.
Please remove the old structure. Currently i'm using new structure with vue-cli & webpack for bundling. Thanks
