### ISSUE TITLE
inject menus, forms and layout options from rest api / orm schemas

### ISSUE THREAD

**Issue by roscopecoltran** [rorikurniadi/vuejs-AdminLTE#5]
Hi,

Hop you are all well !

I was wondering if there is a way to inject or generate dynamically the admin interface, with its options/components from some rest api definitions ?

I am working on golang based backend api and needed to bundle it with a nice admin interface.

My global vision of it is to export my schemas , with [ezorm](https://github.com/ezbuy/ezorm/blob/master/example/blog/blog.yaml), update the yaml file with some vue.js specific properties, but I lake of experience with vue.js bindings ^^.

Example of my intent but in react and not bridging database schema unfortunatelly: [link](http://marmelab.com/admin-on-rest-demo/)

Is there any way to extend your **vuejs-AdminLTE** project for such purpose ?

Have a nice day ! And thanks for any feedback in advance.

Cheers,
Richard

**Comment by rorikurniadi** [comment]
Hi @roscopecoltran,

I have a project https://github.com/rorikurniadi/vue-task which backend is golang (https://github.com/rorikurniadi/go-task) build with Gin Framework and GORM orm. admin theme based on vuejs-AdminLte. you can test by install my go-task project and run vue-task together.
contact me if you need assist. hope I answered your question.

**Comment by r0r1** [comment]
Hi @roscopecoltran,

I have a project https://github.com/rorikurniadi/vue-task which backend is golang (https://github.com/rorikurniadi/go-task) build with Gin Framework and GORM orm. admin theme based on vuejs-AdminLte. you can test by install my go-task project and run vue-task together.
contact me if you need assist. hope I answered your question.
